// Static in-memory seed data — no database required

const commerciaux = [
  { id: 1, nom: 'Renaud', prenom: 'Thomas', email: 'thomas.renaud@forestcrm.fr', tel: '06 12 34 56 78', region: 'Auvergne-Rhône-Alpes', objectif_mensuel_eur: 80000, avatar_initiales: 'TR', actif: true },
  { id: 2, nom: 'Dubois', prenom: 'Marie', email: 'marie.dubois@forestcrm.fr', tel: '06 23 45 67 89', region: 'Nouvelle-Aquitaine', objectif_mensuel_eur: 70000, avatar_initiales: 'MD', actif: true },
  { id: 3, nom: 'Perrin', prenom: 'Julien', email: 'julien.perrin@forestcrm.fr', tel: '06 34 56 78 90', region: 'Grand Est', objectif_mensuel_eur: 60000, avatar_initiales: 'JP', actif: true },
];

const prospects = [
  { id: 1,  nom: 'Forêt Privée Martin', type: 'privé', region: 'Auvergne-Rhône-Alpes', departement: 'Isère', surface_ha: 120, tel: '04 76 11 22 33', email: 'martin.foret@gmail.com', contact_nom: 'Henri Martin', commercial_id: 1, statut: 'qualifié', score: 4, source: 'Recommandation', notes: 'Grande propriété, très motivé pour une coupe sélective.', created_at: '2025-10-01T00:00:00Z', updated_at: '2025-12-22T00:00:00Z' },
  { id: 2,  nom: 'GFA Les Cèdres', type: 'GFA', region: 'Nouvelle-Aquitaine', departement: 'Dordogne', surface_ha: 350, tel: '05 53 44 55 66', email: 'contact@gfa-cedres.fr', contact_nom: 'Sophie Lacombe', commercial_id: 2, statut: 'devis_envoyé', score: 5, source: 'Foire forestière', notes: 'GFA actif, 4 associés. Besoin urgent de coupes.', created_at: '2025-10-15T00:00:00Z', updated_at: '2025-12-20T00:00:00Z' },
  { id: 3,  nom: 'Commune de Thiers', type: 'collectivité', region: 'Auvergne-Rhône-Alpes', departement: 'Puy-de-Dôme', surface_ha: 85, tel: '04 73 80 10 20', email: 'mairie@thiers.fr', contact_nom: 'Jean-Paul Morin', commercial_id: 1, statut: 'négociation', score: 4, source: 'Démarchage', notes: 'Budget voté en conseil municipal. Délais serrés.', created_at: '2025-10-20T00:00:00Z', updated_at: '2025-12-19T00:00:00Z' },
  { id: 4,  nom: 'ONF Vosges Est', type: 'ONF', region: 'Grand Est', departement: 'Vosges', surface_ha: 2400, tel: '03 29 64 20 10', email: 'vosges-est@onf.fr', contact_nom: 'Isabelle Gruber', commercial_id: 3, statut: 'qualifié', score: 3, source: "Appel d'offres", notes: "Grand compte, processus long. À suivre sur 6 mois.", created_at: '2025-11-01T00:00:00Z', updated_at: '2025-12-22T00:00:00Z' },
  { id: 5,  nom: 'SCI Domaine des Pins', type: 'SCI', region: "Provence-Alpes-Côte d'Azur", departement: 'Var', surface_ha: 60, tel: '04 94 33 44 55', email: 'domainedespins@sci.fr', contact_nom: 'Marc Fuentes', commercial_id: 2, statut: 'à_contacter', score: 2, source: 'Site web', notes: 'Premier contact par formulaire. À qualifier.', created_at: '2025-11-20T00:00:00Z', updated_at: '2025-12-30T00:00:00Z' },
  { id: 6,  nom: 'Forêt Bourget', type: 'privé', region: 'Grand Est', departement: 'Bas-Rhin', surface_ha: 45, tel: '03 88 12 23 34', email: 'bourget.foret@orange.fr', contact_nom: 'Paul Bourget', commercial_id: 3, statut: 'gagné', score: 5, source: 'Recommandation', notes: 'Contrat signé. Chantier planifié.', created_at: '2025-09-01T00:00:00Z', updated_at: '2025-09-20T00:00:00Z' },
  { id: 7,  nom: 'Coopérative Bois Massif Central', type: 'coopérative', region: 'Auvergne-Rhône-Alpes', departement: 'Haute-Loire', surface_ha: 890, tel: '04 71 55 66 77', email: 'contact@coop-boismc.fr', contact_nom: 'Céline Vidal', commercial_id: 1, statut: 'devis_envoyé', score: 4, source: 'Salon forestier', notes: 'Coopérative de 12 membres. Décision collective.', created_at: '2025-11-10T00:00:00Z', updated_at: '2025-12-28T00:00:00Z' },
  { id: 8,  nom: 'GFA Forêt Landaise', type: 'GFA', region: 'Nouvelle-Aquitaine', departement: 'Landes', surface_ha: 520, tel: '05 58 77 88 99', email: 'gfa-landaise@sfr.fr', contact_nom: 'Robert Dumas', commercial_id: 2, statut: 'qualifié', score: 5, source: 'Recommandation', notes: 'Pin maritime, 3 coupes à planifier sur 2 ans.', created_at: '2025-11-15T00:00:00Z', updated_at: '2025-12-26T00:00:00Z' },
  { id: 9,  nom: 'Commune de Gérardmer', type: 'collectivité', region: 'Grand Est', departement: 'Vosges', surface_ha: 310, tel: '03 29 63 00 00', email: 'foret@gerardmer.fr', contact_nom: 'Alain Schmitt', commercial_id: 3, statut: 'à_contacter', score: 3, source: 'Démarchage', notes: 'Contacté par courrier. Relance prévue.', created_at: '2025-11-25T00:00:00Z', updated_at: '2025-12-08T00:00:00Z' },
  { id: 10, nom: 'Propriété Dumont', type: 'privé', region: 'Bourgogne-Franche-Comté', departement: "Côte-d'Or", surface_ha: 78, tel: '03 80 22 33 44', email: 'dumont.foret@wanadoo.fr', contact_nom: 'Françoise Dumont', commercial_id: 1, statut: 'perdu', score: 2, source: 'Recommandation', notes: 'A choisi un concurrent local.', created_at: '2025-10-05T00:00:00Z', updated_at: '2025-11-30T00:00:00Z' },
  { id: 11, nom: 'ONF Pyrénées', type: 'ONF', region: 'Occitanie', departement: 'Ariège', surface_ha: 1800, tel: '05 61 02 30 00', email: 'pyrenees@onf.fr', contact_nom: 'Laurent Castel', commercial_id: 2, statut: 'négociation', score: 4, source: "Appel d'offres", notes: "Réponse à appel d'offres déposée. En attente.", created_at: '2025-09-15T00:00:00Z', updated_at: '2025-12-23T00:00:00Z' },
  { id: 12, nom: 'SCI Pinèdes du Sud', type: 'SCI', region: 'Occitanie', departement: 'Gard', surface_ha: 95, tel: '04 66 55 44 33', email: 'pinedes-sud@laposte.net', contact_nom: 'Anne-Marie Blanc', commercial_id: 2, statut: 'qualifié', score: 3, source: 'Site web', notes: 'Propriété mixte pins/chênes. Intéressée par entretien.', created_at: '2025-11-28T00:00:00Z', updated_at: '2025-12-12T00:00:00Z' },
  { id: 13, nom: 'Coopérative Sylva Alsace', type: 'coopérative', region: 'Grand Est', departement: 'Haut-Rhin', surface_ha: 1200, tel: '03 89 41 55 00', email: 'contact@sylva-alsace.fr', contact_nom: 'Georg Müller', commercial_id: 3, statut: 'devis_envoyé', score: 5, source: 'Salon forestier', notes: 'Très grande coopérative, fort potentiel commercial.', created_at: '2025-11-20T00:00:00Z', updated_at: '2025-12-29T00:00:00Z' },
  { id: 14, nom: 'Forêt Chambon', type: 'privé', region: 'Centre-Val de Loire', departement: 'Creuse', surface_ha: 200, tel: '05 55 61 70 80', email: 'chambon.foret@gmail.com', contact_nom: 'Pierre Chambon', commercial_id: 1, statut: 'qualifié', score: 4, source: 'Foire forestière', notes: 'Chênaie de qualité. Projet de coupe sélective.', created_at: '2025-12-01T00:00:00Z', updated_at: '2025-12-28T00:00:00Z' },
  { id: 15, nom: 'Commune de Pontarlier', type: 'collectivité', region: 'Bourgogne-Franche-Comté', departement: 'Doubs', surface_ha: 420, tel: '03 81 46 48 00', email: 'foret@pontarlier.fr', contact_nom: 'Sylvie Jacquet', commercial_id: 3, statut: 'à_contacter', score: 2, source: 'Démarchage', notes: 'Forêt communale. Dossier à constituer.', created_at: '2025-12-05T00:00:00Z', updated_at: '2025-12-20T00:00:00Z' },
];

const chantiers = [
  { id: 1, prospect_id: 6,  nom: 'Coupe Bourget Automne 2025', type: 'coupe_sélective', surface_ha: 28,  montant_ht: 42000,  statut: 'en_cours',  date_debut: '2025-10-15', date_fin_prevue: '2025-12-20', avancement_pct: 65, chef_chantier: 'Marc Tessier',    engins: 'Abatteuse Ponsse, Débardeur Komatsu',        notes: 'Bonne météo. Rendement supérieur aux prévisions.', created_at: '2025-10-15T00:00:00Z' },
  { id: 2, prospect_id: 2,  nom: 'Éclaircie GFA Cèdres',       type: 'éclaircie',       surface_ha: 80,  montant_ht: 38000,  statut: 'démarrage', date_debut: '2026-01-10', date_fin_prevue: '2026-03-30', avancement_pct: 12, chef_chantier: 'Bruno Sauvage',   engins: 'Porteur Vimek 608',                          notes: "Démarrage retardé suite aux pluies. Terrain instable.", created_at: '2025-12-20T00:00:00Z' },
  { id: 3, prospect_id: 3,  nom: 'Entretien Forêt Communale Thiers', type: 'entretien', surface_ha: 40,  montant_ht: 18500,  statut: 'en_cours',  date_debut: '2025-11-03', date_fin_prevue: '2026-01-15', avancement_pct: 78, chef_chantier: 'Éric Morel',     engins: 'Tracteur Fendt 939',                         notes: "Travaux d'élagage en cours. Avancement correct.", created_at: '2025-10-25T00:00:00Z' },
  { id: 4, prospect_id: 8,  nom: 'Coupe Rase Landes Secteur A', type: 'coupe_rase',     surface_ha: 120, montant_ht: 96000,  statut: 'planifié',  date_debut: '2026-02-01', date_fin_prevue: '2026-05-30', avancement_pct: 0,  chef_chantier: 'Serge Delmas',    engins: 'Abatteuse Tigercat, Débardeur John Deere',  notes: "Accès route forestière à valider avec la mairie.", created_at: '2025-12-20T00:00:00Z' },
  { id: 5, prospect_id: 11, nom: 'Débardage Pyrénées Parcelle 7', type: 'débardage',    surface_ha: 55,  montant_ht: 29000,  statut: 'retard',    date_debut: '2025-09-01', date_fin_prevue: '2025-11-30', avancement_pct: 45, chef_chantier: 'Antoine Rivière', engins: 'Câble aérien Konrad',                        notes: 'Panne câble aérien. Pièces commandées, reprise prévue semaine prochaine.', created_at: '2025-09-01T00:00:00Z' },
];

const devis = [
  { id: 1, prospect_id: 2,  commercial_id: 2, montant_ht: 38000,  statut: 'envoyé',   date_envoi: '2025-12-01', date_validite: '2026-01-15', notes: 'Devis éclaircie 80ha. Client en réflexion.',         created_at: '2025-12-01T00:00:00Z' },
  { id: 2, prospect_id: 3,  commercial_id: 1, montant_ht: 18500,  statut: 'accepté',  date_envoi: '2025-10-20', date_validite: '2025-11-20', notes: 'Accepté avec acompte 30%.',                          created_at: '2025-10-20T00:00:00Z' },
  { id: 3, prospect_id: 6,  commercial_id: 3, montant_ht: 42000,  statut: 'accepté',  date_envoi: '2025-09-15', date_validite: '2025-10-15', notes: 'Signé. Chantier démarré.',                           created_at: '2025-09-15T00:00:00Z' },
  { id: 4, prospect_id: 7,  commercial_id: 1, montant_ht: 67000,  statut: 'envoyé',   date_envoi: '2025-12-10', date_validite: '2026-02-10', notes: "En attente du vote de la coopérative.",             created_at: '2025-12-10T00:00:00Z' },
  { id: 5, prospect_id: 11, commercial_id: 2, montant_ht: 29000,  statut: 'accepté',  date_envoi: '2025-08-20', date_validite: '2025-09-20', notes: 'Chantier démarré mais retard prise.',                created_at: '2025-08-20T00:00:00Z' },
  { id: 6, prospect_id: 13, commercial_id: 3, montant_ht: 115000, statut: 'envoyé',   date_envoi: '2025-12-15', date_validite: '2026-02-28', notes: 'Grand compte. Suivi hebdomadaire.',                  created_at: '2025-12-15T00:00:00Z' },
  { id: 7, prospect_id: 1,  commercial_id: 1, montant_ht: 31000,  statut: 'brouillon', notes: 'En cours de rédaction. Métrés à finaliser.',                                                               created_at: '2025-12-18T00:00:00Z' },
  { id: 8, prospect_id: 8,  commercial_id: 2, montant_ht: 96000,  statut: 'envoyé',   date_envoi: '2025-12-20', date_validite: '2026-03-01', notes: 'Grand projet Landes. Réunion prévue en janvier.',    created_at: '2025-12-20T00:00:00Z' },
];

const activites = [
  { id: 1,  prospect_id: 1,  commercial_id: 1, type: 'visite',  titre: 'Visite terrain Forêt Martin',        description: "Parcours des 120ha. Marquage des arbres à couper identifié.",             date_action: '2025-11-15', statut_apres: 'qualifié' },
  { id: 2,  prospect_id: 1,  commercial_id: 1, type: 'appel',   titre: 'Appel suivi Martin',                 description: "Point sur le projet. Envoi devis prévu semaine prochaine.",              date_action: '2025-12-01', statut_apres: 'qualifié' },
  { id: 3,  prospect_id: 2,  commercial_id: 2, type: 'devis',   titre: 'Envoi devis GFA Cèdres',             description: "Devis éclaircie 80ha envoyé par email + courrier.",                      date_action: '2025-12-01', statut_apres: 'devis_envoyé' },
  { id: 4,  prospect_id: 2,  commercial_id: 2, type: 'relance', titre: 'Relance GFA Cèdres',                 description: "Appel de relance. Réunion des associés prévue le 15/01.",               date_action: '2025-12-20', statut_apres: 'devis_envoyé' },
  { id: 5,  prospect_id: 3,  commercial_id: 1, type: 'contrat', titre: 'Signature contrat Thiers',           description: "Contrat signé en mairie. Acompte 30% encaissé.",                        date_action: '2025-10-25', statut_apres: 'gagné' },
  { id: 6,  prospect_id: 4,  commercial_id: 3, type: 'email',   titre: 'Email présentation ONF Vosges',      description: "Envoi plaquette commerciale et références chantiers ONF.",               date_action: '2025-11-05', statut_apres: 'qualifié' },
  { id: 7,  prospect_id: 4,  commercial_id: 3, type: 'visite',  titre: 'Réunion ONF Épinal',                 description: "Rencontre avec Isabelle Gruber. Présentation de 3 scénarios.",           date_action: '2025-12-03', statut_apres: 'qualifié' },
  { id: 8,  prospect_id: 5,  commercial_id: 2, type: 'appel',   titre: 'Premier contact SCI Pins',           description: "Appel qualification. Propriétaire intéressé mais hésitant.",            date_action: '2025-12-05', statut_apres: 'à_contacter' },
  { id: 9,  prospect_id: 6,  commercial_id: 3, type: 'contrat', titre: 'Signature Bourget',                  description: "Contrat coupe sélective signé. Chantier planifié mi-octobre.",           date_action: '2025-09-20', statut_apres: 'gagné' },
  { id: 10, prospect_id: 7,  commercial_id: 1, type: 'devis',   titre: 'Devis Coopérative Massif Central',   description: "Devis 67k€ pour coupe rase et reboisement envoyé.",                     date_action: '2025-12-10', statut_apres: 'devis_envoyé' },
  { id: 11, prospect_id: 8,  commercial_id: 2, type: 'visite',  titre: 'Visite Landes Secteur A et B',       description: "2 jours de terrain. Cartographie GPS réalisée. Volume estimé 4800m³.", date_action: '2025-11-28', statut_apres: 'qualifié' },
  { id: 12, prospect_id: 8,  commercial_id: 2, type: 'devis',   titre: 'Envoi devis Landes',                 description: "Devis 96k€ coupe rase 120ha envoyé.",                                   date_action: '2025-12-20', statut_apres: 'devis_envoyé' },
  { id: 13, prospect_id: 9,  commercial_id: 3, type: 'email',   titre: 'Email Gérardmer',                    description: "Envoi courrier de présentation suite démarchage postal.",                date_action: '2025-12-08', statut_apres: 'à_contacter' },
  { id: 14, prospect_id: 11, commercial_id: 2, type: 'note',    titre: 'Note retard Pyrénées',               description: "Panne câble aérien. Pièces commandées chez Konrad. Reprise +7 jours.", date_action: '2025-11-20', statut_apres: 'négociation' },
  { id: 15, prospect_id: 12, commercial_id: 2, type: 'appel',   titre: 'Qualification SCI Pinèdes',          description: "Appel avec Anne-Marie Blanc. Intéressée par entretien régulier sur 3 ans.", date_action: '2025-12-12', statut_apres: 'qualifié' },
  { id: 16, prospect_id: 13, commercial_id: 3, type: 'devis',   titre: 'Devis Sylva Alsace',                 description: "Devis 115k€ pour gestion pluriannuelle envoyé.",                        date_action: '2025-12-15', statut_apres: 'devis_envoyé' },
  { id: 17, prospect_id: 14, commercial_id: 1, type: 'visite',  titre: 'Visite Chênaie Chambon',             description: "Belle propriété. Chênes de 80-120 ans. Fort potentiel pour coupe sélective haut de gamme.", date_action: '2025-12-18', statut_apres: 'qualifié' },
  { id: 18, prospect_id: 1,  commercial_id: 1, type: 'relance', titre: 'Relance Martin',                     description: "Relance téléphonique. Accord de principe pour le projet.",               date_action: '2025-12-22', statut_apres: 'qualifié' },
  { id: 19, prospect_id: 3,  commercial_id: 1, type: 'appel',   titre: 'Point avancement Thiers',            description: "Chantier à 78%. Fin prévue 15 janvier. Client satisfait.",              date_action: '2025-12-19', statut_apres: 'gagné' },
  { id: 20, prospect_id: 7,  commercial_id: 1, type: 'relance', titre: 'Relance Coopérative',                description: "Vote de la coopérative le 8 janvier. Devis valide jusqu'au 10 février.", date_action: '2025-12-28', statut_apres: 'devis_envoyé' },
  { id: 21, prospect_id: 2,  commercial_id: 2, type: 'visite',  titre: "Visite terrain Cèdres",              description: "Validation des pistes d'accès. Plan d'intervention finalisé.",          date_action: '2025-11-10', statut_apres: 'qualifié' },
  { id: 22, prospect_id: 6,  commercial_id: 3, type: 'note',    titre: 'Compte-rendu chantier Bourget',      description: "Avancement 65%. Qualité bois excellente. Prévision fin décembre.",       date_action: '2025-12-10', statut_apres: 'gagné' },
  { id: 23, prospect_id: 4,  commercial_id: 3, type: 'relance', titre: 'Relance ONF Vosges',                 description: "Appel au service technique. Dossier en commission le 20/01.",           date_action: '2025-12-22', statut_apres: 'qualifié' },
  { id: 24, prospect_id: 10, commercial_id: 1, type: 'note',    titre: 'Perte Dumont - Analyse',             description: "Client perdu pour un concurrent 15% moins cher. À noter pour ajustement tarifs.", date_action: '2025-11-30', statut_apres: 'perdu' },
  { id: 25, prospect_id: 15, commercial_id: 3, type: 'email',   titre: 'Email Pontarlier',                   description: "Premier contact par email. Présentation services. Réponse attendue.",   date_action: '2025-12-20', statut_apres: 'à_contacter' },
  { id: 26, prospect_id: 11, commercial_id: 2, type: 'appel',   titre: 'Point reprise chantier Pyrénées',    description: "Confirmation reprise lundi. Pièces reçues. Planning réajusté.",          date_action: '2025-12-23', statut_apres: 'négociation' },
  { id: 27, prospect_id: 8,  commercial_id: 2, type: 'appel',   titre: 'Confirmation réunion Landes',        description: "Réunion confirmée le 8 janvier avec Robert Dumas et ses 3 associés.",   date_action: '2025-12-26', statut_apres: 'devis_envoyé' },
  { id: 28, prospect_id: 13, commercial_id: 3, type: 'relance', titre: 'Suivi Sylva Alsace',                 description: "Appel hebdomadaire. Décision du CA prévue fin janvier.",                date_action: '2025-12-29', statut_apres: 'devis_envoyé' },
  { id: 29, prospect_id: 5,  commercial_id: 2, type: 'relance', titre: 'Relance SCI Pins',                   description: "Deuxième appel. RDV visite terrain fixé au 10 janvier.",               date_action: '2025-12-30', statut_apres: 'à_contacter' },
  { id: 30, prospect_id: 14, commercial_id: 1, type: 'email',   titre: 'Envoi offre Chambon',                description: "Proposition commerciale préliminaire envoyée. Attente retour.",         date_action: '2025-12-28', statut_apres: 'qualifié' },
];

module.exports = { commerciaux, prospects, chantiers, devis, activites };
